import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Splash } from '@/comp/Splash'
import { Settings, defaultSettings } from '@/types';
import { Overlay } from '@/comp/Overlay';
import rainbowStyles from '@/styles/Rainbow.module.css';
import { Fullscreen } from '@/comp/Fullscreen';

export default function Home() {
  const [settings, setSettings] = useState<Settings>(defaultSettings());
  const [confirmed, setConfirmed] = useState(false);

  useEffect(() => {
    if (window.location.search.includes('skip')) {
      setConfirmed(true);
    }
  }, [setConfirmed]);

  return (
    <>
      <Head>
        <title>Floss</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={rainbowStyles.rainbow}>
        {confirmed ? (
          <Fullscreen settings={settings} />
        ) : (
          <Splash settings={settings} onConfirm={() => setConfirmed(true)} />
        )}
        <Overlay settings={settings} setSettings={setSettings} />
      </main>
    </>
  )
}
